#!/bin/bash
# USAGE: start|stop
#
case "$1" in
start)
echo "Starting IPv6 Tunnel Server."
cd /home/bradjc
sudo /home/bradjc/server
;;
stop)
echo "Stopping IPv6 Tunnel Server."
sudo pkill -9 server
;;

*)
echo “IPv6 Tunnel”
echo $”Usage: $0 {start|stop}”
exit 1
esac
exit 0