#!/bin/bash
# USAGE: start|stop
#
case "$1" in
start)
echo "Starting IPv6 Tunnel Client."
cd /home/bradjc
sudo /home/bradjc/ipv6tunnel-client
;;
stop)
echo "Stopping IPv6 Tunnel Client."
sudo pkill -9 ipv6server-client
;;

*)
echo “IPv6 Tunnel”
echo $”Usage: $0 {start|stop}”
exit 1
esac
exit 0